---

- name: Configure PostgreSQL APT key
  apt_key: 
    url: "{{ postgresql_apt_key_url }}" 
    state: present

- name: Configure PostgreSQL APT repository
  apt_repository: 
    repo: "{{ postgresql_apt_repo }}"
    state: present

- name: Install Barman package
  apt: 
    pkg: "{{ item.pkg }}"
    state: "{{ item.state }}"
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - { pkg: "barman",            state: "present" }
    - { pkg: "postgresql-client", state: "latest"  } # for pg_receivexlog
